[project]
name = "s1-pyphenix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bioio>=3.0.0",
    "bioio-tifffile>=1.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
]
